spring:
  profiles:
    active: pro
  jackson:
    time-zone: GMT+8
  http:
    encoding:
      charset: UTF-8
  output:
    ansi:
      enabled: detect
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.leif.knowme.model
  config-location: classpath:mybatis/mybatis-config.xml
logging:
  path: logs
