server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://192.168.253.129:3306/knowme
    username: root
    password: 650728
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  secret: javainuse
km:
  wx-app-id: wxappid
  wx-secret: wxsecret